services:
  app:
    container_name: home-library-rest-service
    build: .
    restart: on-failure
    image: tatsianashulha/home-library-rest-service
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    networks:
      - ${NAME}
  
  postgres:
    image: tatsianashulha/home-library_database
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - ${NAME}

volumes:
  postgres: {}

networks:
  home-library-rest-service:
    name: ${NAME}
    driver: bridge